  # =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

# configuration update for https://github.com/pzaborowski/pygeoapi
# "Iliad - Digital Twin of the Ocean"
# use cases made by: Piotr Zaborowski
#
# =================================================================

server:
    bind:
        host: 127.0.0.1
        port: 5002
    url: http://localhost:5002
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'


logging:
    level: DEBUG
    #logfile: /tmp/pygeoapi.log

metadata:
    linked-data:
        collections-context: https://ogcincubator.github.io/geodcat-ogcapi-records/build/annotated/geo/geodcat/geodcat-records/context.jsonld
    identification:
        title:
            en: Pygeoapi Iliad demo instance
            fr: instance par défaut de pygeoapi
        description:
            en: this instance is based on the official pygeoapi distribution with some addons in pzaborowski/pygeoapi fork. It contains small layer visualisation enhancements, support of zarr and netCDF in EDR, extended linked data support on the collection level.
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    my-observations-linked:
        type: collection
        title: Observations linked
        description: My cool observations with definitions
        keywords:
            - observations
            - monitoring
        linked-data:
            direct-context:
              - https://ogcincubator.github.io/iliad-apis-features/build/annotated/hosted/iliad/api/features/oim-obs/context.jsonld
              - https://raw.githubusercontent.com/ILIAD-ocean-twin/OIM/47b1aaa3ba6bbf513665993b7bbb8c04b0e162b7/jsonld/oimOceanProfile-context.jsonld
              - https://raw.githubusercontent.com/ILIAD-ocean-twin/OIM/main/jsonld/crossDomain-context.jsonld
              - https://raw.githubusercontent.com/ILIAD-ocean-twin/OIM/main/jsonld/metadata-context.jsonld
        links:
            - type: text/csv
              rel: canonical
              title: data
              href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
            - type: text/csv
              rel: alternate
              title: data
              href: https://raw.githubusercontent.com/mapserver/mapserver/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
        extents:
            spatial:
                bbox: [ 34,31,35,32 ]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2024-01-30T18:24:39Z
                end: 2024-04-30T08:57:29Z
        providers:
            - type: feature
              name: CSVObs
              data: ~/Temp/JF_Israel_Jun_2011-Dec_2023_DwC_Format_25.3.2024-JF_Jun_2011-Dec_2023_DwC_Format_25.3.2024-pp.csv
              id_field: occurenceID
              geometry:
                  x_field: decimalLongitude
                  y_field: decimalLatitude
              properties_obj:
                  hasResult:
                    - scientificName
                    - occurrenceStatus
                    - basisOfRecord
                    - scientificNameID
                    - recordedBy
                    - quantificationMethod
                    - organismQuantity
                    - organismQuantityType
                    - sampleSizeUnit
                    - sampleSizeValue
                    - coordinateUncertaintyInMeters
                    - strandedJellyfish
                    - distanceWalkedinmeters
