# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

# configuration update for
# "Iliad - Digital Twin of the Ocean"
# use cases made by: Piotr Zaborowski
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5002
    url: http://localhost:5002
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

    
logging:
    level: DEBUG
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    influx-edr:
        type: collection
        title: SINTEF observatories data
        description: EDR test with sintef influx data
        keywords:
            - edr
            - salinity
            - sea_water_temperature
            - template
        extents:
            spatial:
                bbox: [ 11.6646680,58.9355836,11.6646690,58.9355850 ]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        linked-data:
          context:
            - http://covjson.org/context.jsonld
        links:
            - type: text/html
              rel: canonical
              hreflang: en-US
              href: http://localhost:5002/influx-edr
              title: base url
            - type: application/json
              rel: canonical
              hreflang: en-US
              href: http://localhost:5002/collections/influx-edr/cube?bbox=10,58,12,60&datetime=2023-05-01T02:25:00Z/2023-05-01T02:30:00Z&f=json&parameter_names=sea_water_temperature
              title: example json-ld query all properties by 2D bbox (10.4,35.5,11.26,36.31) coordinates and time slice 2023-07-16T02:00Z - 2023-07-16T02:00Z and sea_water_temperature
            - type: text/html
              rel: canonical
              hreflang: en-US
              href: http://localhost:5002/collections/influx-edr/cube?bbox=10,58,12,60&datetime=2023-05-01T02:25:00Z/2023-05-01T02:30:00Z
              title: example html query all properties by 2D bbox (10.4,35.5,11.26,36.31) coordinates and time slice 2023-07-16T02:00Z - 2023-07-16T02:00Z
        providers:
            - type: edr
              name: influx-edr
              # InfluxDBProvider config
              data:
                token_variable: "SINTEF_influx_token"
                bucket: "oceanlab"
                url: "https://oceanlab.azure.sintef.no:8086"
              baseURI: "https://sintef.twin-ocean.eu/data/"
#              x_field: lon
#              y_field: lat
#              time_field: time
              time_api_label: t
              locations:
                - name: munkholmen
                  location:
                    point:
                      - 11.6646684
                      - 58.9355841
                  parameters:
                    sea_water_temperature: ctd_temperature_munkholmen
                    sea_water_salinity: ctd_salinity_munkholmen
                  tables:
                    ctd_temperature_munkholmen:
                      sea_water_temperature: temperature
                      approved: approved
                    ctd_salinity_munkholmen:
                      sea_water_salinity: salinity
                      approved: approved
              parameters:
                sea_water_temperature:
                  type: Quantity
                  cj_type: PointSeries
                  id: sea_water_temperature
                  name: sea_water_temperature
                  data_type: float
                  description: Sea water temperature is the in situ temperature of the sea water
                  description_lang: en
                  unit_label: degree_Celsius
                  unit_label_lang: en
                  unit_symbol: Cel
                  unit_type: float
                  observed_property_id: http://vocab.nerc.ac.uk/standard_name/sea_water_temperature/
                  observed_property_label: Sea Water Temperature
                  observed_property_label_lang: en
                  observed_property_description: observed_property_description
                  observed_property_description_lang: en
                  min_value: 0
                  max_value: 100
                  properties:
                    sensor: http://link.to-sta/sensor
                approved:
                  id: measurement_approved
                  name: measurement_approved
                  label: providers approved
                  label_lang: en
                  type: Category
                  cj_type: PointSeries
                  data_type: category
                  description: "yes if passed a data quality filter, no if not, none if no filter applied"
                  description_lang: en
                  unit_label: degree_Celsius
                  unit_label_lang: en
                  unit_symbol: Cel
                  unit_type: integer
                  observed_property_id: http://id3iliad.example.com/observedProperties/approved
                  min_value: 0
                  max_value: 1
                  observed_property_label: measurement_approved
                  observed_property_label_lang: en
                  observed_property_description: Categorical property determining if the the measurement
                    passed a quality assessment
                  observed_property_description_lang: en
                  observed_property_categories:
                    - id: http://id3iliad.example.com/observedProperties/approved/yes
                      label: "yes"
                      label_lang: en
                    - id: http://id3iliad.example.com/observedProperties/approved/no
                      label: "no"
                      label_lang: en
                  properties:
                    seeAlso: https://docs.influxdata.com/influxdb/v1.3/concepts/key_concepts/
                  categoryEncoding:
                    http://id3iliad.example.com/observedProperties/approved/yes: 1
                    http://id3iliad.example.com/observedProperties/approved/no: 0
                    "yes": 1
                    "no": 0

              format:
                  name: coveragejson
                  mimetype: application/json
