# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5003
    url: http://localhost:5003
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: DEBUG
    # logfile: ~/tmp/pygeoapi.log
metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    munkholmen:
        type: collection
        title: EDR version of the munholmen data time series
        description: SST example netCDF data via EDR API as coverage
        keywords:
            - edr
            - sst
            - timeseries
        extents:
            spatial:
                bbox: [10.38, 63.45, 10.38, 63.45]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              hreflang: en-US
              href: http://localhost:5003/swan-edr
              title: base url
            - type: text/html
              rel: canonical
              hreflang: en-US
              href: http://localhost:5003/collections/munkholmen/position?coords=POINT(-10.38 63.45)&datetime=2024-10-16
              title: example html query all prameters by POINT(10.38 63.45) coordinates and time slice 2024-10-16
            - type: text/html
              rel: canonical
              hreflang: en-US
              href: http://localhost:5003/collections/munkholmen/position?coords=POINT(-10.38 63.45)&datetime=2024-10-16&parameter-name=Temperature
              title: example html query sst by POINT(10.38 63.45) coordinates and time slice 2024-10-16
            - type: app/json
              rel: canonical
              hreflang: en-US
              href: http://localhost:5003/collections/munkholmen/position?coords=POINT(-10.38 63.45)&datetime=2024-10-16&parameter-name=Temperature&f=json&parameter-name=hs
              title: example json query sst by POINT(10.38 63.45) coordinates and time slice 2024-10-16
        providers:
            - type: edr
              name: xarray-edr-timeseries
              data: "/Users/piotr/Downloads/NCEI_timeSeries_template_v2.0_2016-09-22_181830.715665.nc"
             # optionally specify x/y/time fields, else provider will attempt
             # to derive automagically
              lon: 
                - 10.38
              lat:
                - 63.45
              x_field: lon
              y_field: lat
              time_field: time
              time_api_label: t
              domainType: PointSeries
              context:
                - https://ogcincubator.github.io/iliad-apis-features/build/annotated/hosted/iliad/api/features/coverageJSON/context.jsonld
                - https://raw.githubusercontent.com/ILIAD-ocean-twin/data_access_api/refs/heads/main/examples/EDR_sintef/PointSeries_covjson_context.json
              format:
                name: netcdf
                mimetype: application/x-netcdf

