

    # TilesOnWMTS:
    #     type: collection
    #     title: GLOBAL_ANALYSISFORECAST_PHY_001_024
    #     description: GLOBAL_ANALYSISFORECAST_PHY_001_024
    #     keywords:
    #         - tiles
    #         - wmts wrapper
    #         - Global Ocean Physics Analysis and Forecast
    #     links:
    #         - type: image/png
    #           rel: source
    #           title: data
    #           href: https://wmts.marine.copernicus.eu/teroWmts/GLOBAL_ANALYSISFORECAST_PHY_001_024/cmems_mod_glo_phy-cur_anfc_0.083deg_PT6H-i_202211
    #           hreflang: en-US
    #     extents:
    #         spatial:
    #             bbox: [ -180,-90,180,90 ]
    #             crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    #         temporal:
    #             begin: 2000-10-30T18:24:39Z
    #             end: 2007-10-30T08:57:29Z
    #     providers:
    #         - type: tile
    #           name: WMTSFacade
    #           data: https://wmts.marine.copernicus.eu/teroWmts
    #           format:
    #             name: png  # png or jpeg
    #             mimetype: image/png
    #           options:
    #             wmts_layer: GLOBAL_ANALYSISFORECAST_PHY_001_024/cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m_202406/uo # the layer name of the wmts
    #             wmts_tile_matrix_set: EPSG:3857@3x  # the name of the tile matrix set of the wmts.
    #             scheme: WebMercatorQuad  # the aligning scheme in pygeoapi.
    #             zoom:
    #               min: 0
    #               max: 20
    # MapOnWMS:
    #   type: collection
    #   title: AVHRR Pathfinder Version 5.3 L3-Collated (L3C) SST, Global, 0.0417°, 1981-present, Daytime (1 Day Composite) - dt_analysis
    #   description: Advanced Very High Resolution Radiometer (AVHRR) Pathfinder Version 5.3 L3-Collated (L3C) sea surface temperature. This netCDF-4 file contains sea surface temperature (SST) data produced as part of the AVHRR Pathfinder SST Project. These data were created using Version 5.3 of the Pathfinder algorithm and the file is nearly but not completely compliant with the Global High-Resolution Sea Surface Temperature (GHRSST) Data Specifications V2.0 (GDS2). The sses_bias and sses_standard_deviation variables are empty. Full compliance with GDS2 specifications will be achieved in the future Pathfinder Version 6. These data were created by the NOAA National Centers for Environmental Information (NCEI).\n\ncdm_data_type = Grid\nVARIABLES (all of which use the dimensions [time][latitude][longitude]):\nsea_surface_temperature (NOAA Climate Data Record of sea surface skin temperature, degree_C)\ndt_analysis (deviation from last SST analysis, degree_C)\nwind_speed (10m wind speed, m s-1)\nsea_ice_fraction (%)\nquality_level (quality level of SST pixel, 1)\npathfinder_quality_level (Pathfinder SST quality flag, 1)\nl2p_flags (1)\n
    #   keywords:
    #       - high-resolution
    #       - wms wrapper
    #       - pathfinder
    #   links:
    #       - type: text/html
    #         rel: source
    #         title: data source
    #         href: https://coastwatch.pfeg.noaa.gov/erddap/info/nceiPH53sstd1day/index.htmlTable
    #         hreflang: en-US
    #   extents:
    #       spatial:
    #           bbox: [ -180,-90,180,90 ]
    #           crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    #       temporal:
    #           begin: 1981-01-01T00:00:00Z
    #           end: 2024-05-30T08:57:29Z
    #   providers:
    #     - type: map
    #       name: WMSFacade
    #       data: https://coastwatch.pfeg.noaa.gov/erddap/wms/nceiPH53sstd1day/request
    #       options:
    #         layer: nceiPH53sstd1day:dt_analysis
    #       format:
    #         name: png
    #         mimetype: image/png

    SkyfishSST:
      type: collection
      title: Iliad terrasigna pilot WMS proxy with semantic alignment to the OIM, Skyfish SST
      description: experimental setup with pygeoapi
      keywords:
          - water 
      links:
          - type: text/html
            rel: source
            title: data source
            href: https://iliad.terrasigna.io/geoportal.html
            hreflang: en-US
      extents:
          spatial:
              bbox: [ 27.442684715513632,42.176573854950696,32.43651871922607,46.84954433053188]
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          temporal:
              begin: 2018-01-01T02:00:00.000Z
              end: 2020-12-31T02:00:00.000Z
      providers:
        - type: map
          name: WMSFacade
          data: https://ddd.terrasigna.com/geoserver-skyfish/skyfish/wms
          options:
            layer: skyfish:sst_BS_L4_010_006
          format:
            name: png
            mimetype: image/png
    CMEMS_forecast_SSS:
      type: collection
      title: Iliad terrasigna pilot WMS proxy with semantic alignment to the OIM, Gebco
      description: experimental setup with pygeoapi
      keywords:
          - vosaline
          - ImageMosaic
          - WCS
          - CMEMS
          - Forecast
      links:
          - type: text/html
            rel: source
            title: data source
            href: https://iliad.terrasigna.io/geoportal.html
            hreflang: en-US
          - type: image/png
            rel: source
            title: full map in CRS:84, WIDTH=319, HEIGHT=299
            href: https://ddd.terrasigna.com/geoserver-skyfish/skyfish/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=27.44166730213788696,42.18000051133176243,32.43166730213788895,46.85000051133176413&CRS=CRS:84&WIDTH=319&HEIGHT=299&LAYERS=CMEMS_forecast_SSS&STYLES=SSS&FORMAT=image/png&DPI=72&TRANSPARENT=TRUE
            hreflang: en-US
      extents:
          spatial:
              bbox: [ 27.442684715513632,42.176573854950696,32.43651871922607,46.84954433053188]
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          temporal:
              begin: 2018-01-01T02:00:00.000Z
              end: 2020-12-31T02:00:00.000Z
      providers:
        - type: map
          name: WMSFacade
          data: https://ddd.terrasigna.com/geoserver-skyfish/skyfish/wms
          options:
            layer: CMEMS_forecast_SSS
            style: SSS
          format:
            name: png
            mimetype: image/png
#SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap
#&BBOX=27.44166730213788696,42.18000051133176243,32.43166730213788895,46.85000051133176413&
#CRS=CRS:84&WIDTH=319&
#HEIGHT=299&LAYERS=ILIAD_gebco&STYLES=
#&FORMAT=image/png&DPI=72&MAP_RESOLUTION=72&FORMAT_OPTIONS=dpi:72&

#TRANSPARENT=TRUE

#https://ddd.terrasigna.com/geoserver-skyfish/skyfish/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=27.44166730213788696,42.18000051133176243,32.43166730213788895,46.85000051133176413&CRS=CRS:84&WIDTH=319&HEIGHT=299&LAYERS=CMEMS_forecast_SSS&STYLES=SSS&FORMAT=image/png&DPI=72&TRANSPARENT=TRUE

#https://ddd.terrasigna.com/geoserver-skyfish/skyfish/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=27.44166730213788696,42.18000051133176243,32.43166730213788895,46.85000051133176413&CRS=CRS:84&WIDTH=319&HEIGHT=299&LAYERS=skyfish:sst_BS_L4_010_006&STYLES=&FORMAT=image/png&DPI=72&MAP_RESOLUTION=72&FORMAT_OPTIONS=dpi:72&TRANSPARENT=TRUE
#https://ddd.terrasigna.com/geoserver-skyfish/skyfish/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=27.44166730213788696,42.18000051133176243,32.43166730213788895,46.85000051133176413&CRS=CRS:84&WIDTH=319&HEIGHT=299&LAYERS=skyfish:sst_BS_L4_010_006&STYLES=ILIAD_gebco&FORMAT=image/png&DPI=72&TRANSPARENT=TRUE

#f=png&service=WMS&request=GetMap&layers=&styles=&format=image%2Fjpeg&transparent=true&version=1.1.1&width=256&height=256&srs=EPSG%3A4326&bbox=-180,0,0,85.0511287798066